### ISSUE TITLE
Check USB thumb drives on the CM4 bundle 

### ISSUE THREAD

**Issue by mikegapinski** [tesla-android/android-raspberry-pi#14]
:bug: :thread:When plugging USB stick in to CM4, Android OS file browser doesn’t detect the stick.
The same USB stick is detected by RPI-4B running same version of Tesla Android (2023.36.1). Stick is FAT32 filesystem & 32GB in size. I tried both USB pots that are next to the CM4 HDMI.

**Comment by mikegapinski** [comment]
Hw related

**Comment by 2695565746q-alt** [comment]
Hello, my good friend. Tesla Android cm4 does not recognize the USB flash drive. I have installed the latest version of the compilation system TeslaAndroid-2025.14.1-RELEASE-cm4-single-image-installer.img, but it still cannot recognize the USB flash drive. However, the mouse and keyboard can be successfully recognized and used. Later, I tried to connect cm4 to a Windows computer using a TYPE-C data cable for adb connection to the Android system of cm4. Even though I have installed the adb driver, there is no beep sound indicating device recognition when I plug the data cable into a Windows 10 computer. Could you please help me solve this problem? Thank you
