### ISSUE TITLE
sound not working

### ISSUE THREAD

**Issue by smdx2** [tesla-android/android-raspberry-pi#18]
sound is not working on v2023.38.1. Was working OK on 2023.36 (although waze seemed more stable in this last

**Comment by mikegapinski** [comment]
Enable it in the settings

**Comment by smdx2** [comment]
It was enabled. Also tried to change volume in the settings, and nothing
happened

A quarta, 27/09/2023, 07:13, Michał Gapiński ***@***.***>
escreveu:

**Comment by mikegapinski** [comment]
In this case you’d need to clear the browser data and reboot the car. Sometimes the OS cuts the audio for all websites, not only the TA app

Wysyłane z aplikacji Outlook dla systemu iOS<https://aka.ms/o0ukef>
________________________________
Od: smdx2 ***@***.***>
Wysłane: Wednesday, September 27, 2023 8:26:38 AM
Do: tesla-android/android-raspberry-pi ***@***.***>
DW: Michał Gapiński ***@***.***>; Comment ***@***.***>
Temat: Re: [tesla-android/android-raspberry-pi] sound not working (Issue #18)


It was enabled. Also tried to change volume in the settings, and nothing
happened

A quarta, 27/09/2023, 07:13, Michał Gapiński ***@***.***>
escreveu:

**Comment by smdx2** [comment]
Also tried on an android tablet. Also not working. Reverted back to
previous version and is working on both again

A quarta, 27/09/2023, 07:28, Michał Gapiński ***@***.***>
escreveu:

**Comment by smdx2** [comment]
Tested again on the new version (2023.40.2) using a fresh install, and problem remains.  Any log or something that I might provide to pinpoint the possible problem?

**Comment by MagoKimbra** [comment]
Same problem with 2024.18.2 version...
