### ISSUE TITLE
Full screen is not full screen

### ISSUE THREAD

**Issue by GtHbbrr** [tesla-android/android-raspberry-pi#23]
When I switch to full screen using the TA full screen button the TA canvas is full screen but the Android canvas is not full screen. 
Could be because of the max resolution of 832p. 
Can you add a 1200p resolution so full screen will be full screen also in Android?
![IMG_5140](https://github.com/tesla-android/android-raspberry-pi/assets/66380559/ae09263a-2b6a-4257-b91c-9d09ea1acfc6)
![IMG_5018](https://github.com/tesla-android/android-raspberry-pi/assets/66380559/e536ae85-3b71-4482-a547-c3fd96335c9d)

**Comment by mikegapinski** [comment]
This is not the right place for support requests, there is a dedicated repository for this: https://github.com/tesla-android/issue-tracker/issues
