### ISSUE TITLE
Removal of the ability to disable Hotspot kills ability to use a 3rd party router

### ISSUE THREAD

**Issue by dmayo305** [tesla-android/android-raspberry-pi#24]
Removing the hotspot toggle from settings makes it very difficult to latch onto a mobile hostpot/router, which is my desired configuration.
I can hook my Pi into a monitor and mouse and get the hotspot to turn off (which apparently automatically returns on boot). I can also get connected to my mobile router. But, then, I can't get a connection directly through the Pi's IP address. Nor can I get the settings page to show actual settings via localhost on the Pi, or via the internal IP address on another device connected to the same mobile router (ie 192.168.0.136)
![PXL_20240109_151132706 MP](https://github.com/tesla-android/android-raspberry-pi/assets/13510358/6c5f26a6-ee95-4433-9f62-974bea27904a)

**Comment by chilman408** [comment]
Agreed, I think having the ability to connect to Tesla Android directly via IP cleans up my HW configuration a lot using the Pi4.

I think the last version that supported this was on 2023.20.1.1.  Correct me if I'm wrong?

**Comment by MagoKimbra** [comment]
I would also like to use my cell as a mobile hotspot and connect the PI4 to the cell and Tesla to the cell, to avoid having to buy another SIM.
But if I do this I can't enter the Tesla-Android page.

**Comment by mikegapinski** [comment]
This is not the right place for support requests, there is a dedicated repository for this: https://github.com/tesla-android/issue-tracker/issues
