### ISSUE TITLE
Bluetooth internet disconnects after few minutes

### ISSUE THREAD

**Issue by iamcalvintam** [tesla-android/android-raspberry-pi#26]
It seems like the raspberry pi 4 will disconnect from bluetooth internet after a few minutes, at which point it will no longer function. Bluetooth shows up as turned off and toggling it does nothing.

**Comment by weitzman** [comment]
Probably a duplicate issue of https://github.com/tesla-android/issue-tracker/issues/304

**Comment by iamcalvintam** [comment]
Ah didnt realise issues were tracked at that location, will close this issue as a duplicate thanks!

**Comment by iamcalvintam** [comment]
Duplicate of issue : [https://github.com/tesla-android/issue-tracker/issues/304](https://github.com/tesla-android/issue-tracker/issues/304)
