### ISSUE TITLE
Possibility to connect to home wifi instead of lte

### ISSUE THREAD

**Issue by petertijsma** [tesla-android/android-raspberry-pi#27]
Hi,

Is it possible, or if not, would it be an idea, to connect the TeslaAndroid box to the home Wifi if the car is in range of the home network.
This way, the Tesla could still automatically download updates through the TeslaAndroid box when connected to home wifi without using mobile data.
Another advantage would be to, for example, download Netflix movies on the box for when going on holiday for the kids. This would also save a lot of mobile data. 

Thanks!

**Comment by efkosk** [comment]
Tesla blocks local IP addresses (192.168...) You can try it. From Tesla you can't get to the router's web for example. I guess that's why it's handled this way.  There are ways to trick it and get there locally, but I guess there is a reason why it doesn't work by default. I would like to know it.

**Comment by mikegapinski** [comment]
This is not the right place for support requests, there is a dedicated repository for this: https://github.com/tesla-android/issue-tracker/issues
