### ISSUE TITLE
First boot is fine, second boot no wifi is coming up

### ISSUE THREAD

**Issue by Ashram56** [tesla-android/android-raspberry-pi#30]
Good afternoon,

Just trying to setup Tesla Android Project on a RPI4 devkit.

First boot is fine (although it takes a while), I can see the Tesla Android wifi coming up. However on subsequent power on (in car or directly powered by the original RPI PSU), the Wifi network does not come up anymore.

Note: subsequent attempt to reflash the micro SD card using RPI Imager under Windows fail, it cannot erase partitions. Also getting a failure using Balena Etcher.

**Comment by mikegapinski** [comment]
This is not the right place for support requests, there is a dedicated repository for this: https://github.com/tesla-android/issue-tracker/issues
